#!/usr/bin/env python3
"""
Regenerate mla_offsets.h from libagame.so.
Usage: python get_offsets.py /path/to/libagame.so > jni/mla_offsets.h
"""
import struct, sys

def generate(path):
    with open(path, 'rb') as f:
        data = f.read()

    shoff = struct.unpack_from('<Q', data, 0x28)[0]
    shnum = struct.unpack_from('<H', data, 0x3C)[0]
    shentsize = struct.unpack_from('<H', data, 0x3A)[0]
    shstrndx = struct.unpack_from('<H', data, 0x3E)[0]
    shstrtab_off = struct.unpack_from('<Q', data, shoff + shstrndx * shentsize + 0x18)[0]

    def get_name(idx):
        if idx == 0: return ''
        end = data.find(b'\x00', shstrtab_off + idx)
        return data[shstrtab_off + idx:end].decode('ascii', errors='replace')

    sym_info = str_info = None
    for i in range(shnum):
        sh_off = shoff + i * shentsize
        sh_type = struct.unpack_from('<I', data, sh_off + 4)[0]
        name = get_name(struct.unpack_from('<I', data, sh_off)[0])
        if sh_type == 11:
            saddr = struct.unpack_from('<Q', data, sh_off + 0x10)[0]
            soff = struct.unpack_from('<Q', data, sh_off + 0x18)[0]
            ssize = struct.unpack_from('<Q', data, sh_off + 0x20)[0]
            sym_info = (saddr, soff, ssize)
        elif name == '.dynstr':
            saddr = struct.unpack_from('<Q', data, sh_off + 0x10)[0]
            soff = struct.unpack_from('<Q', data, sh_off + 0x18)[0]
            ssize = struct.unpack_from('<Q', data, sh_off + 0x20)[0]
            str_info = (saddr, soff, ssize)

    sym_addr, sym_off, sym_size = sym_info
    str_addr, str_off, str_size = str_info

    lines = []
    lines.append('// Auto-generated by get_offsets.py')
    lines.append('// Source: ' + path.split('\\')[-1])
    lines.append('')
    lines.append('#ifndef MLA_OFFSETS_H')
    lines.append('#define MLA_OFFSETS_H')
    lines.append('')

    for i in range(sym_size // 24):
        off = sym_off + i * 24
        st_name = struct.unpack_from('<I', data, off)[0]
        st_value = struct.unpack_from('<Q', data, off + 8)[0]
        if st_name == 0 or st_name >= str_size:
            continue
        name_bytes = data[str_off + st_name:str_off + st_name + 80]
        name = name_bytes.split(b'\x00')[0].decode('ascii', errors='replace')
        if name.startswith('lua_') or name.startswith('tolua_'):
            define = 'OFF_' + name.upper().replace('.', '_')
            lines.append('#define {:<45s} 0x{:08x}ULL'.format(define, st_value))

    lines.append('')
    lines.append('#endif')
    return '\n'.join(lines)

if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) > 1 else r'C:\Users\NGEONG\Videos\MLA\libagame.so'
    print(generate(path))
